import {readFile,writeFile} from 'node:fs/promises';
let js=await readFile('src/original.js','utf8');
const enhancements=await readFile('src/enhancements.js','utf8');
const conversion=await readFile('src/conversion.js','utf8');
const btStart=js.indexOf('function BT(){'),btEnd=js.indexOf('function HT(){',btStart);
const headerEnhancements=enhancements.slice(0,enhancements.indexOf('function Iv('));
js=js.slice(0,btStart)+conversion+'\n'+headerEnhancements+'\n'+js.slice(btEnd);
const ivStart=js.indexOf('function Iv('),ivEnd=js.indexOf('function dA(',ivStart);
const voiceEnhancements=enhancements.slice(enhancements.indexOf('function Iv('));
js=js.slice(0,ivStart)+voiceEnhancements+'\n'+js.slice(ivEnd);
const a=js.indexOf('function cA(){'),b=js.indexOf('function uA(',a);
let hero=js.slice(a,b);
hero=hero.replace('const t=M.useRef(null)','const t=M.useRef(null)');
hero=hero.replace('children:"Start talking."','children:o.jsx(FlowHeadline,{})');
hero=hero.replace('o.jsxs("h1",{id:"fb-title",children:', 'o.jsxs("h1",{id:"fb-title","aria-label":"Stop typing. Start talking. It’s free.",children:');
hero=hero.replace('children:[o.jsxs("h1",{id:"fb-title"', 'children:[o.jsx("span",{className:"flow-eyebrow",children:"FREE AI VOICE TYPING FOR MAC"}),o.jsxs("h1",{id:"fb-title"');
hero=hero.replace('children:"Speak naturally. Flow does the typing."','children:"Hold fn and speak naturally. Flow removes filler words, understands corrections, and types polished text in any Mac app."');
hero=hero.replace('o.jsx(rt,{children:"Get Flow free"})','o.jsx(FlowHeroActions,{})');
hero=hero.replace('href:"#dictation-demo",className:"fb-keycap","aria-label":"See Flow turn speech into text"','href:"#dictation-demo",className:"fb-keycap","aria-label":"Try Flow with the function key",onClick:e=>{e.preventDefault();window.dispatchEvent(new CustomEvent("flow:fn-trigger"))}');
hero=hero.replace('o.jsxs(K.div,{className:"fb-hero-fragment fb-hero-fragment-left"','o.jsxs(K.a,{href:"#dictation-demo",className:"fb-hero-fragment fb-hero-fragment-left"');
hero=hero.replace('transition:{delay:.9},"aria-hidden":"true",children:','transition:{delay:.9},"aria-label":"Hear how Flow cleans up speech",children:');
hero=hero.replace('o.jsxs(K.div,{className:"fb-hero-fragment fb-hero-fragment-right"','o.jsxs(K.a,{href:"#dictation-demo",className:"fb-hero-fragment fb-hero-fragment-right"');
hero=hero.replace('transition:{delay:1},"aria-hidden":"true",children:','transition:{delay:1},"aria-label":"See Flow turn speech into ready text",children:');
hero=hero.replace('o.jsxs("a",{className:"ed-hero-cue",href:"#dictation-demo",children:[o.jsx("span",{children:"SEE IT FLOW"}),o.jsx($s,{size:18})]})','o.jsx(FnHoldCue,{})');
hero=hero.replace('children:[o.jsxs("div",{className:"ed-hero-copy"','children:[o.jsx("div",{className:"spectrum-field","aria-hidden":"true",children:o.jsx("video",{src:"/assets/hero-gradient-loop.mp4?v=conversion",autoPlay:!0,muted:!0,loop:!0,playsInline:!0,preload:"metadata"})}),o.jsxs("div",{className:"ed-hero-copy"');
hero=hero.replace('transition:{delay:.45,duration:.7}', 'transition:{delay:.28,duration:.55}');
js=js.slice(0,a)+(await readFile('src/hero.js','utf8'))+'\n'+hero+js.slice(b);
js=js.replace('function $v(){return o.jsxs("section",{className:"fb-apps",id:"your-apps",children:[o.jsx(Ne,{children:o.jsxs("h2",{children:["Same apps.",o.jsx("br",{}),o.jsx("em",{children:"Less typing."})]})}),o.jsx("div",{className:"fb-app-grid",children:Jv.map((t,s)=>o.jsx(hA,{index:s},t.name))}),o.jsxs("div",{className:"fb-apps-foot",children:[o.jsxs("span",{children:[o.jsx(Ad,{}),"Slack, and your other apps too."]}),o.jsx("small",{children:"Illustrated examples"})]})]})}','function $v(){return o.jsxs("section",{className:"fb-apps",id:"your-apps",children:[o.jsx(Ne,{children:o.jsxs("h2",{children:["Same apps.",o.jsx("br",{}),o.jsx("em",{children:"Less typing."})]})}),o.jsx("div",{className:"fb-app-grid",children:Jv.map((t,s)=>o.jsx(hA,{index:s},t.name))})]})}');
js=js.replace('initial:t?!1:{y:-35,rotate:-12},whileInView:{y:0,rotate:-7},viewport:{once:!0,amount:.5},transition:{type:"spring",stiffness:125,damping:13}','initial:t?!1:{opacity:0,scale:.65,y:-38,rotate:-12},whileInView:{opacity:1,scale:1,y:0,rotate:-7},viewport:{once:!0,amount:.5},transition:{type:"spring",stiffness:120,damping:14,delay:.12}');
js=js.replace('"wispr-ribbon")})','"focused-bold")})');
js=js.replaceAll('start 144px','start 88px');
js=js.replace('children:["Compare plans",o.jsx(Ft,{size:15})]','children:["View plans",o.jsx(Ft,{size:15})]');
js=js.replace(',!1,o.jsx(aN,{})]})',',!1]})');
js=js.replaceAll('o.jsx(rt,{children:"Get Flow free"})','o.jsx(FlowPrimaryCTA,{})');
js=js.replace('Sign up free. Install Runable on your Mac.','Download free. Install Runable on your Mac.');
js=js.replace('Flow is available in the Runable app for Mac. Create your free account, install the app and follow the Flow setup instructions.','Flow is available in the Runable app for Mac. Download the app and follow the Flow setup instructions.');
js=js.replace('const mA=[{q:"Is Flow really free?"', 'const mA=[{q:"How is Flow different from built-in dictation?",a:"Built-in dictation transcribes speech. Flow also removes fillers, understands spoken corrections, and leaves polished text for you to review."},{q:"Does Flow send anything for me?",a:"No. Flow places text where your cursor is. You review, edit and send it yourself."},{q:"What should I know about privacy?",a:"Flow needs microphone access to hear your speech. Review Runable’s privacy policy and data controls before enabling access."},{q:"Is Flow really free?"');
js=js.replace('function pA(){return o.jsxs("div",{className:"editorial-page editorial-type focused-bold-page",children:[o.jsx(cA,{}),o.jsx(Wv,{}),o.jsx($v,{}),o.jsx(eb,{}),o.jsx(tb,{}),o.jsx(nb,{}),o.jsx(sb,{}),o.jsx(Sn,{})]})}', 'function pA(){return o.jsxs("div",{className:"editorial-page editorial-type focused-bold-page",children:[o.jsx(FlowMeasurement,{}),o.jsx(cA,{}),o.jsx(FlowProofStrip,{}),o.jsx(Wv,{}),o.jsx(FlowWhySection,{}),o.jsx($v,{}),o.jsx(eb,{}),o.jsx(FlowTrustSection,{}),o.jsx(tb,{}),o.jsx(nb,{}),o.jsx(sb,{}),o.jsx(Sn,{})]})}');
await writeFile('dist/assets/site.js',js);
await writeFile('dist/assets/site.css',(await readFile('src/original.css','utf8'))+'\n'+await readFile('src/theme.css','utf8')+'\n'+await readFile('src/conversion.css','utf8'));
await writeFile('dist/assets/hero-video.json',await readFile('src/hero-video.json','utf8'));
await writeFile('dist/index.html',await readFile('src/index.html','utf8'));
console.log('Built full Flow site with original content and motion.');
